spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hairshop
    username: root
    password: dkssud123!

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
#    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true

  profiles:
    include: private

cloud:
  aws:
    s3:
      bucket: hairshop-bucket
      upload-temp: img/upload/temp/
    credentials:
      access-key: AKIAYS2NWB65H77RIN4P
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging.level:
  org.hibernate.SQL: debug
